---
apiVersion: apps/v1

kind: Deployment

metadata:
  name: {{.Release.Name}}-deployment
  namespace: {{.Values.environment}}
  labels:
    app: {{.Release.Name}}-deployment
  annotations:
    checkov.io/skip1: CKV_K8S_43=App images use unique tags

spec:
  replicas: {{.Values.minReplicaCount}}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{.Release.Name}}-pod

#  strategy:
#    type: RollingUpdate
#    rollingUpdate:
#      maxSurge: 10%
#      maxUnavailable: 10%

  template:
    metadata:
      labels:
        app: {{.Release.Name}}-pod
    
    spec:
      containers:
        - name: {{.Release.Name}}-pod
          image: {{.Values.imageRepository}}/{{.Values.imageName}}:{{.Chart.AppVersion}}
          imagePullPolicy: Always

          ports:
            - containerPort: {{.Values.appPort}}

          resources:
            requests:
              cpu: 270m
              memory: 210Mi
            limits:
              cpu: 500m
              memory: 300Mi

          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 10201
            runAsGroup: 20201
            capabilities:
              drop:
                - NET_RAW
                - ALL

          livenessProbe:
            httpGet:
              path: /
              port: {{.Values.appPort}}
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /
              port: {{.Values.appPort}}
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3

          startupProbe:
            httpGet:
              path: /
              port: {{.Values.appPort}}
            timeoutSeconds: 1
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5

          volumeMounts:
            - name: firestore-credentials-volume
              mountPath: "/usr/src/app/secret"
              readOnly: true

      volumes:
        - name: firestore-credentials-volume
          secret:
            secretName: firestore-credentials

      imagePullSecrets:
        - name: nhl-app-registry

      automountServiceAccountToken: false
