---
apiVersion: v1

kind: Service

metadata:
  name: {{.Release.Name}}-service
  namespace: {{.Values.environment}}

spec:
  type: ClusterIP
  selector:
    app: {{.Release.Name}}-pod
  ports:
    - protocol: TCP
      port: {{.Values.appPort}}
      targetPort: {{.Values.appPort}}
