---
apiVersion: v2
appVersion: "0.1.0"
name: nhl-app
version: 0.1.0
description: Chart for my diploma application
type: application
keywords:
  - application
maintainers:
  - email: kasperskiyoleg@yandex.ru
    name: Oleg Kaspersky
home: "https://gitlab.koi-projects.ru/epam-diploma/app"


dependencies:
- name: ingress-nginx
  version: 4.0.17
  repository: https://kubernetes.github.io/ingress-nginx
